### ISSUE TITLE
request for depends_on keycloak module

### ISSUE THREAD

**Issue by generalpax** [iits-consulting/terraform-opentelekomcloud-project-factory#60]
i would like to add dependencies to create keycloak server first or something else:

changed and tested:

keycloak_idp.tf

```bash
resource "opentelekomcloud_identity_protocol_v3" "saml" {
  protocol    = "saml"
  provider_id = opentelekomcloud_identity_provider_v3.provider.id
  mapping_id  = opentelekomcloud_identity_mapping_v3.mapping.id

  metadata {
    domain_id = data.opentelekomcloud_identity_project_v3.current.domain_id
    metadata  = data.curl.saml_descriptor.response
  }

  depends_on = [ var.otc_tf_dependencies ]
}
```

variables.tf
```bash
variable "otc_tf_dependencies" {
  type        = list
  description = "The list of ressource dependencies. For example the compute instance which is configured outside of the module: opentelekomcloud_compute_instance_v2"
}
```

idp.tf
```bash
module "otc_keycloak_sso" {
    source               = "registry.terraform.io/iits-consulting/project-factory/opentelekomcloud//modules/keycloak_sso"
    ...
    otc_tf_dependencies = [ opentelekomcloud_compute_instance_v2.keycloak ]
   ...
```

**Comment by canaykin** [comment]
Greetings,

This can simply be achieved by adding `depends_on` to the module call:

```hcl
module "otc_keycloak_sso" {
    source               = "registry.terraform.io/iits-consulting/project-factory/opentelekomcloud//modules/keycloak_sso"
    ...
    depends_on = [ opentelekomcloud_compute_instance_v2.keycloak ]
   ...
```

The code you provided is a workaround from the past before the module dependency syntax was added ([version 0.13](https://github.com/hashicorp/terraform/blob/v0.13/CHANGELOG.md#0130-august-10-2020)). It achieves this by using explicit dependency syntax `depends on` to extend an implicit dependency.

In more detail,
```hcl
depends_on = [ var.otc_tf_dependencies ]
```
this will create an explicit dependency between the resource and the variable, not what is inside the variable. 

The second part;
```hcl
module "otc_keycloak_sso" {
    source               = "registry.terraform.io/iits-consulting/project-factory/opentelekomcloud//modules/keycloak_sso"
    ...
    otc_tf_dependencies = [ opentelekomcloud_compute_instance_v2.keycloak ]
   ...
```
creates an implicit dependency between the values passed to the module variable `otc_tf_dependencies `, namely, resource `opentelekomcloud_compute_instance_v2.keycloak` and the variable itself. The complete dependency chain becomes:
```
opentelekomcloud_identity_protocol_v3.saml = explicit => var.otc_tf_dependencies = implicit => opentelekomcloud_compute_instance_v2.keycloak
```
this does accomplish the goal of granular dependency control between modules but is essentially a hack designed to overcome the limitations of old terraform versions.

Since there is the much simpler and readble option to create module level dependencies, I am unsure if this is really needed.

Best,
Can
